-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: legal_document_chunk_embeddings
-- Purpose:   pgvector RAG store for structure-aware legal document chunks.
--            Each row holds one semantic chunk + its 1024-dim embedding vector.
--            Enables cosine similarity search via <=> operator (pgvector).
-- Run with:  psql $DATABASE_URL -f legal_rag_chunks.sql
-- ─────────────────────────────────────────────────────────────────────────────

-- Ensure pgvector extension is installed (requires superuser or rds_superuser).
CREATE EXTENSION IF NOT EXISTS vector;

-- ── Main table ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS "legal_document_chunk_embeddings" (
  "id"           VARCHAR        NOT NULL,
  "workspace_id" VARCHAR        NOT NULL,
  "case_id"      VARCHAR        NOT NULL,
  "document_id"  VARCHAR        NOT NULL,
  "chunk_index"  INTEGER        NOT NULL,
  "content"      TEXT           NOT NULL,
  "category"     VARCHAR(64)    NOT NULL DEFAULT 'sonstiges',
  "keywords"     VARCHAR[]      NOT NULL DEFAULT '{}',
  "quality_score" DOUBLE PRECISION NOT NULL DEFAULT 0.5,
  "embedding"    vector(1024),
  "created_at"   TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),
  "updated_at"   TIMESTAMPTZ(3) NOT NULL DEFAULT NOW(),

  CONSTRAINT "legal_document_chunk_embeddings_pkey" PRIMARY KEY ("id")
);

-- ── Unique constraint: one row per (workspace, document, chunk position) ──────
ALTER TABLE "legal_document_chunk_embeddings"
  DROP CONSTRAINT IF EXISTS "legal_chunk_embeddings_unique";
ALTER TABLE "legal_document_chunk_embeddings"
  ADD CONSTRAINT "legal_chunk_embeddings_unique"
  UNIQUE ("workspace_id", "document_id", "chunk_index");

-- ── Indexes ───────────────────────────────────────────────────────────────────
-- Case-scoped lookups (DELETE by case, stats per case)
CREATE INDEX IF NOT EXISTS "legal_chunk_embeddings_case_idx"
  ON "legal_document_chunk_embeddings" ("workspace_id", "case_id");

-- pgvector HNSW index for fast approximate cosine search
-- HNSW is preferred over IVFFlat for < 1M rows — no training phase required.
CREATE INDEX IF NOT EXISTS "legal_chunk_embeddings_vector_idx"
  ON "legal_document_chunk_embeddings"
  USING hnsw ("embedding" vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- ── GIN index for keyword full-text fallback (when embedding is NULL) ─────────
CREATE INDEX IF NOT EXISTS "legal_chunk_embeddings_fts_idx"
  ON "legal_document_chunk_embeddings"
  USING gin (to_tsvector('german', "content"));

-- ── Comments ──────────────────────────────────────────────────────────────────
COMMENT ON TABLE "legal_document_chunk_embeddings" IS
  'Structure-aware legal document chunks with pgvector embeddings. '
  'Generated by the subsumio document processing pipeline. '
  'Searched via cosine similarity (<=> operator) with gemini-embedding-001 (1024 dims).';

COMMENT ON COLUMN "legal_document_chunk_embeddings"."embedding" IS
  'Dense vector embedding (1024 dims, gemini-embedding-001). NULL if embedding service unavailable.';
COMMENT ON COLUMN "legal_document_chunk_embeddings"."chunk_index" IS
  'Zero-based position of this chunk within the document.';
COMMENT ON COLUMN "legal_document_chunk_embeddings"."category" IS
  'Legal document category (sachverhalt, rechtsausfuehrung, antrag, etc.)';
COMMENT ON COLUMN "legal_document_chunk_embeddings"."quality_score" IS
  'Chunk quality score 0..1 from document processing pipeline.';
